version: '3.8'

services:
  # --- MICROSERVICIOS ---
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - broker
      - keycloak
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/resto
      - RABBIT_URL=amqp://guest:guest@broker:5672
      # URL interna para validar tokens
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/resto
      # URL para que el front/postman obtenga el token
      - KEYCLOAK_AUTH_URL=http://localhost:8080/realms/resto/protocol/openid-connect/token
    restart: unless-stopped
    networks:
      - app-network

  servicio-cocina:
    build: ./servicio-cocina
    container_name: cocina
    depends_on:
      - mongo
      - broker
    environment:
      - MONGO_URL=mongodb://mongo:27017/resto
      - RABBIT_URL=amqp://guest:guest@broker:5672
    restart: unless-stopped
    networks:
      - app-network

  # --- INFRAESTRUCTURA ---
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - "5672:5672"   # Protocolo AMQP
      - "15672:15672" # Dashboard Web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

  # --- SEGURIDAD (OBLIGATORIO) ---
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - app-network

  # --- OBSERVABILIDAD (OBLIGATORIO) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limita RAM para que no explote tu PC
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

volumes:
  mongo-data:
  elastic-data:

networks:
  app-network:
    driver: bridge