services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-init
      - broker
    environment:
      # API
      - API_PORT=3000

      # Mongo
      - MONGO_URL=mongodb://mongo:27017/resto?replicaSet=rs0

      # RabbitMQ
      - RABBIT_URL=amqp://guest:guest@broker:5672

      # Keycloak (lo agregamos despu√©s)
      - JWKS_URI=http://keycloak:8080/realms/resto/protocol/openid-connect/certs

    restart: unless-stopped

  servicio-cocina:
    build: ./servicio-cocina
    container_name: cocina
    depends_on:
      - mongo
      - mongo-init
      - broker
    environment:
      - MONGO_URL=mongodb://mongo:27017/resto?replicaSet=rs0
      - RABBIT_URL=amqp://guest:guest@broker:5672
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    command: ["--replSet","rs0","--bind_ip_all"]
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:6
    depends_on:
      - mongo
    entrypoint: ["bash","-lc","mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo:27017\"}]})' && sleep 2"]

  broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo-data:
